apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search
spec:
  version: 7.17.3
  count: 1
  configRef:
    secretName: elasticsearch-credentials