kind: Secret
apiVersion: v1
metadata:
  name: elastic-credentials
stringData:
  password: {{ .Values.credentials.password }}
  username: {{ .Values.credentials.username }}
---
kind: Secret
apiVersion: v1
metadata:
  name: elasticsearch-credentials
stringData:
  enterprise-search.yml: |-
    elasticsearch.host: {{.Values.elasticHost }}
    elasticsearch.username: {{ .Values.credentials.username }}
    elasticsearch.password: {{ .Values.credentials.password }}
    elasticsearch.ssl.enabled: true
---
kind: Secret
apiVersion: v1
metadata:
  name: kibana
data:
  encryptionkey: {{ .Values.credentials.encryptionKey }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: elastic-certificates
data:
  elastic-certificates.p12: {{ .Files.GetBytes .Values.certificates.p12 | b64enc }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: elastic-certificate-pem
data:
  elastic-certificates.pem: {{ .Files.GetBytes .Values.certificates.pem | b64enc }}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: elastic-certificate-crt
data:
  elastic-certificates.crt: {{ .Files.GetBytes .Values.certificates.crt | b64enc }}
type: Opaque