apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search
spec:
  version: 7.17.3
  count: 1
  configRef:
    secretName: elasticsearch-credentials
---
kind: Secret
apiVersion: v1
metadata:
  name: elasticsearch-credentials
stringData:
  enterprise-search.yml: |-
    elasticsearch.host: https://elastic.kiss-dev.commonground.nu
    elasticsearch.username: elastic
    elasticsearch.password: changeme
    elasticsearch.ssl.enabled: true